version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    image: nestjs-todo-app:development
    ports:
      - '${APP_PORT}:3000'
      - '9229:9229' # Debug port
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: "${DB_PORT:-3306}"
      DB_USERNAME: "${DB_USERNAME:-appuser}"
      DB_PASSWORD: "${DB_PASSWORD:-password}"
      REDIS_HOST: redis
      REDIS_PORT: "${REDIS_PORT:-6379}"
      MONGO_HOST: mongo
      MONGO_PORT: "${MONGO_PORT:-27017}"
      DEBUG: "nestjs:*"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
      - redis
      - mongo
    command: ["/bin/sh", "-c", "./scripts/wait-for-db.sh npm run start:dev -- --preserveWatchOutput"]
    networks:
      - app-network

  mysql:
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  redis:
    ports:
      - '${REDIS_PORT}:6379'

  mongo:
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

networks:
  app-network:
    driver: bridge